##################### 基本設定と依存関係 ##################################

#rubocop_todo.ymlに書いてある内容はルール違反してても無視
inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

# 対象外
AllCops:
  DisplayCopNames: true
  # TargetRubyVersion: 2.6
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'lib/**/*'
    - 'node_modules/**/*'
    - 'config/environments/*'
    - 'config/puma.rb'

  # 新ルールを有効化
  NewCops: enable

# trueかfalseを設定しないと警告が出る
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

##################### スタイル ##################################

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

# ドキュメントの無いpublic classを許可する
Style/Documentation:
  Enabled: false

# !! のイディオムを許可
Style/DoubleNegation:
  Enabled: false

#文字列をfreezeするか
Style/FrozenStringLiteralComment:
  Enabled: false

# selfが無くても良い時に省略するか。model内において、ローカル変数とメソッド呼び出しの区別をつけた方が分かりやすい場合が多い
Style/RedundantSelf:
  Enabled: false

# 文字列リテラルにシングルクォートを使用
Style/StringLiterals:
  EnforcedStyle: single_quotes

##################### レイアウト（コードの整形に関連） ##################################

# タブ文字の使用を禁止（代わりにスペースを使用）
Layout/IndentationStyle:
  Enabled: false

# 複数行にまたがる引数リストの末尾にカンマを付けない
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

# 行の終わりのセミコロンの使用を禁止
Style/Semicolon:
  Enabled: false

##################### メトリクス（コードの複雑さや長さを測定） ##################################

# 変数の代入(A)、メソッドの呼び出し等(B)、条件分岐(C)から算出される複雑度
Metrics/AbcSize:
  Max: 30

# 循環的複雑度 ≒ 分岐の数
Metrics/CyclomaticComplexity:
  Max: 10

# 1行の文字数
Layout/LineLength:
  Max: 100
  Exclude:
    - 'db/migrate/*.rb'

# メソッドの行数
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/migrate/*.rb'
